=== STDombr/oop_course3_semester1/Lab2/Tariff.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema"
           elementFormDefault = "qualified">

    <xs:element name = "Tariffs" type = "tariffInstance"/>
    <xs:complexType name = "tariffInstance">
        <xs:sequence>
            <xs:element name = "tariff" type = "tariff" maxOccurs = "unbounded"/>
        </xs:sequence>
        <xs:attribute name = "name" type = "xs:string" use = "required"/>
    </xs:complexType>

    <xs:complexType name = "tariff">
        <xs:sequence>
            <xs:element name = "name" type = "xs:string"/>
            <xs:element name = "operatorName" type = "xs:string"/>
            <xs:element name = "payroll" type = "xs:double"/>
            <xs:element name = "callPrices">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name = "inNetCallPrice" type = "xs:double"/>
                        <xs:element name = "outNetCallPrice" type = "xs:double"/>
                        <xs:element name = "landlineCallPrice" type = "xs:double"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name = "smsPrice" type = "xs:double"/>
            <xs:element name = "parameters">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name = "countOfFavNumbers" type = "xs:int"/>
                        <xs:element name = "connectionPrice" type = "xs:double"/>
                        <xs:element name = "tariffication" type = "xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name = "id" type = "xs:ID" use = "required"/>
    </xs:complexType>

    <xs:simpleType name="tariffication">
        <xs:restriction base="xs:string">
            <xs:enumeration value = "30 seconds"/>
            <xs:enumeration value = "60 seconds"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="payroll">
        <xs:restriction base = "xs:double">
            <xs:minInclusive value = "0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="inNetCallPrice">
        <xs:restriction base = "xs:double">
            <xs:minInclusive value = "0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="outNetCallPrice">
        <xs:restriction base = "xs:double">
            <xs:minInclusive value = "0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="landlineCallPrice">
        <xs:restriction base = "xs:double">
            <xs:minInclusive value = "0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="smsPrice">
        <xs:restriction base = "xs:double">
            <xs:minInclusive value = "0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="countOfFavNumbers">
        <xs:restriction base = "xs:int">
            <xs:minInclusive value = "0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="connectionPrice">
        <xs:restriction base = "xs:double">
            <xs:minInclusive value = "0"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== STDombr/oop_course3_semester1/Lab2/Tariff1.xml
<?xml version="1.0" encoding="UTF-8"?>

<Tariffs name="Tariff"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="Tariff.xsd">

    <tariff id = "tariff1">
        <name>SuperNet Turbo</name>
        <operatorName>Vodafone</operatorName>
        <payroll>100</payroll>
        <callPrices>
            <inNetCallPrice>0</inNetCallPrice>
            <outNetCallPrice>0</outNetCallPrice>
            <landlineCallPrice>0.5</landlineCallPrice>
        </callPrices>
        <smsPrice>0.5</smsPrice>
        <parameters>
            <countOfFavNumbers>5</countOfFavNumbers>
            <connectionPrice>100</connectionPrice>
            <tariffication>60 seconds</tariffication>
        </parameters>

        <name>SuperNet Turbo</name>
        <operatorName>Vodafone</operatorName>
        <payroll>100</payroll>
        <callPrices>
            <inNetCallPrice>0</inNetCallPrice>
            <outNetCallPrice>0</outNetCallPrice>
            <landlineCallPrice>0.5</landlineCallPrice>
        </callPrices>
        <smsPrice>0.5</smsPrice>
        <parameters>
            <countOfFavNumbers>5</countOfFavNumbers>
            <connectionPrice>100</connectionPrice>
            <tariffication>60 seconds</tariffication>
        </parameters>
    </tariff>

    <tariff id = "tariff2">
        <name>SuperNet Start</name>
        <operatorName>Vodafone</operatorName>
        <payroll>70</payroll>
        <callPrices>
            <inNetCallPrice>0.5</inNetCallPrice>
            <outNetCallPrice>0.5</outNetCallPrice>
            <landlineCallPrice>1</landlineCallPrice>
        </callPrices>
        <smsPrice>1</smsPrice>
        <parameters>
            <countOfFavNumbers>2</countOfFavNumbers>
            <connectionPrice>70</connectionPrice>
            <tariffication>60 seconds</tariffication>
        </parameters>
    </tariff>

    <tariff id = "tariff3">
        <name>SuperNet Pro</name>
        <operatorName>Vodafone</operatorName>
        <payroll>150</payroll>
        <callPrices>
            <inNetCallPrice>0</inNetCallPrice>
            <outNetCallPrice>0</outNetCallPrice>
            <landlineCallPrice>0.5</landlineCallPrice>
        </callPrices>
        <smsPrice>0.5</smsPrice>
        <parameters>
            <countOfFavNumbers>10</countOfFavNumbers>
            <connectionPrice>150</connectionPrice>
            <tariffication>60 seconds</tariffication>
        </parameters>
    </tariff>

    <tariff id = "tariff4">
        <name>SuperNet Unlim</name>
        <operatorName>Vodafone</operatorName>
        <payroll>230</payroll>
        <callPrices>
            <inNetCallPrice>0</inNetCallPrice>
            <outNetCallPrice>0</outNetCallPrice>
            <landlineCallPrice>0</landlineCallPrice>
        </callPrices>
        <smsPrice>0</smsPrice>
        <parameters>
            <countOfFavNumbers>20</countOfFavNumbers>
            <connectionPrice>230</connectionPrice>
            <tariffication>60 seconds</tariffication>
        </parameters>
    </tariff>

</Tariffs>
